/**
 * Story 31.2 (Task A.3): generator for the standalone SessionStart hook script
 * `<projectRoot>/.hammoc/hooks/context-builder.mjs`.
 *
 * The generated `.mjs` runs independently of the Hammoc server at every session
 * start. It is REGENERATED on every manifest save, so the declared file list /
 * variable toggles / acknowledged commands are baked in as a CONFIG literal,
 * while the actual VALUES (file contents, git output, today's date, active BMad
 * story, command stdout) are computed FRESH at runtime (AC2.b/2.c — never
 * snapshotted at generation time).
 *
 * Implementation note — the script body is a `String.raw` template so the regex
 * backslashes (`\s`, `\r`, `\n`) survive into the emitted file verbatim. The two
 * injected values are spliced in via function-replacement (not `${}`
 * interpolation) so a `$` inside a path or command cannot trigger a replacement
 * pattern, and so the body can stay free of `${` entirely.
 */

import type { ContextBuilderManifest } from '@hammoc/shared';

/** The subset of the manifest baked into the generated CONFIG literal. */
interface BakedConfig {
  files: string[];
  variables: ContextBuilderManifest['variables'];
  recentCommitsCount: number;
  /** Only acknowledged commands (AC5.b). */
  customCommands: Array<{ command: string }>;
}

const SCRIPT_BODY = String.raw`// AUTO-GENERATED by Hammoc Context Builder (Story 31.2). DO NOT EDIT BY HAND.
// Source of truth: <projectRoot>/.hammoc/context-builder.json
// This file is overwritten on every manifest save. Edits here are lost.
//
// At every Claude Code SessionStart it prints a JSON envelope on stdout:
//   { "hookSpecificOutput": { "hookEventName": "SessionStart", "additionalContext": "<assembled>" } }
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const PROJECT_ROOT = __PROJECT_ROOT_JSON__;
const CONFIG = __CONFIG_JSON__;

function gitOutput(args) {
  return execSync('git ' + args, {
    cwd: PROJECT_ROOT,
    encoding: 'utf8',
    timeout: 5000,
    stdio: ['ignore', 'pipe', 'ignore'],
  }).trim();
}

function readDevStoryLocation() {
  // Resolve devStoryLocation from .bmad-core/core-config.yaml at runtime (no YAML
  // dependency — a single-line regex is enough). Fallback: docs/stories.
  try {
    const cfg = fs.readFileSync(path.join(PROJECT_ROOT, '.bmad-core', 'core-config.yaml'), 'utf8');
    const lines = cfg.split(/\r?\n/);
    for (const ln of lines) {
      const m = ln.match(/^devStoryLocation:\s*(.+?)\s*$/);
      if (m) return m[1].replace(/^['"]|['"]$/g, '').trim();
    }
  } catch (e) {
    // ignore — fall through to default
  }
  return 'docs/stories';
}

function parseTitle(text, fallback) {
  const lines = text.split(/\r?\n/);
  for (const ln of lines) {
    const m = ln.match(/^#\s+(.+?)\s*$/);
    if (m) return m[1];
  }
  return fallback;
}

function parseStatus(text) {
  const lines = text.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+Status\s*$/.test(lines[i])) {
      for (let j = i + 1; j < lines.length; j++) {
        const t = lines[j].trim();
        if (t) return t;
      }
    }
  }
  return 'unknown';
}

function activeBmadStory() {
  // PO-confirmed definition: the latest-mtime .story.md in devStoryLocation,
  // surfaced as "<title> (Status: <status>)".
  try {
    const storyDir = readDevStoryLocation();
    const dirAbs = path.resolve(PROJECT_ROOT, storyDir);
    const files = fs.readdirSync(dirAbs).filter(function (f) { return f.endsWith('.story.md'); });
    if (files.length === 0) return '(no .story.md files in ' + storyDir + ')';
    let latest = files[0];
    let latestMs = -1;
    for (const f of files) {
      const st = fs.statSync(path.join(dirAbs, f));
      if (st.mtimeMs > latestMs) { latestMs = st.mtimeMs; latest = f; }
    }
    const text = fs.readFileSync(path.join(dirAbs, latest), 'utf8');
    return parseTitle(text, latest) + ' (Status: ' + parseStatus(text) + ')';
  } catch (e) {
    return '(unable to resolve active BMad story)';
  }
}

const blocks = [];

// (a) Reference files — read fresh; missing files become a placeholder so the
// whole script never fails (AC2.c).
for (const rel of CONFIG.files) {
  const abs = path.resolve(PROJECT_ROOT, rel);
  try {
    const content = fs.readFileSync(abs, 'utf8');
    blocks.push('## Reference file: ' + rel + '\n\n' + content);
  } catch (e) {
    blocks.push('## Reference file: ' + rel + '\n\n(파일을 찾을 수 없음: ' + rel + ')');
  }
}

// (b) Built-in dynamic variables — recomputed every run (AC2.b).
if (CONFIG.variables.gitBranch) {
  let v;
  try { v = gitOutput('rev-parse --abbrev-ref HEAD'); } catch (e) { v = '(git unavailable)'; }
  blocks.push('## Current git branch\n\n' + v);
}
if (CONFIG.variables.recentCommits) {
  const n = CONFIG.recentCommitsCount || 5;
  let v;
  try { v = gitOutput('log -n ' + n + ' --pretty=format:%h %s'); } catch (e) { v = '(git unavailable)'; }
  blocks.push('## Recent ' + n + ' commit(s)\n\n' + v);
}
if (CONFIG.variables.uncommittedCount) {
  let v;
  try {
    const out = gitOutput('status --short');
    v = out ? out.split(/\r?\n/).filter(Boolean).length : 0;
  } catch (e) { v = '(git unavailable)'; }
  blocks.push('## Uncommitted file count\n\n' + String(v));
}
if (CONFIG.variables.today) {
  blocks.push('## Today\n\n' + new Date().toISOString().slice(0, 10));
}
if (CONFIG.variables.activeBmadStory) {
  blocks.push('## Active BMad story\n\n' + activeBmadStory());
}

// (c) Acknowledged custom commands (AC5.b) — only acknowledged commands were
// baked into CONFIG.
for (const cc of CONFIG.customCommands) {
  let out;
  try {
    out = execSync(cc.command, { cwd: PROJECT_ROOT, encoding: 'utf8', timeout: 10000 }).trim();
  } catch (e) {
    out = '(command failed: ' + (e && e.message ? e.message : 'error') + ')';
  }
  blocks.push('## Command: ' + cc.command + '\n\n' + out);
}

const additionalContext = blocks.join('\n\n');
process.stdout.write(JSON.stringify({
  hookSpecificOutput: {
    hookEventName: 'SessionStart',
    additionalContext: additionalContext,
  },
}));
`;

/**
 * Build the `.mjs` script text for the given project root + manifest. Only
 * acknowledged custom commands are baked in (AC5.b).
 */
export function buildContextBuilderScript(
  projectRoot: string,
  manifest: ContextBuilderManifest,
): string {
  const config: BakedConfig = {
    files: manifest.files,
    variables: manifest.variables,
    recentCommitsCount: manifest.recentCommitsCount ?? 5,
    customCommands: manifest.customCommands
      .filter((c) => c.acknowledged)
      .map((c) => ({ command: c.command })),
  };

  // Function replacements so a `$` inside a path/command is never treated as a
  // replacement pattern (`$&`, `$1`, ...).
  const projectRootJson = JSON.stringify(projectRoot);
  const configJson = JSON.stringify(config, null, 2);

  return SCRIPT_BODY
    .replace('__PROJECT_ROOT_JSON__', () => projectRootJson)
    .replace('__CONFIG_JSON__', () => configJson);
}
